package QuanLyNVST;


import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HONG THAM
 */
public class LuongNV extends javax.swing.JFrame {

    /**
     * Creates new form LuongNV
     */
    public LuongNV() {
        initComponents();
        this.setTitle("Tính lương");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtLCB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPCCV = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnTinhLuong = new javax.swing.JButton();
        lblTinh = new javax.swing.JLabel();
        txtKetQua = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel4.setBackground(new java.awt.Color(0, 204, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setText("TÍNH LƯƠNG CHO NHÂN VIÊN");
        jPanel2.add(jLabel4);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 60);

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));
        jPanel3.setLayout(null);

        jLabel5.setText("Mã NV");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 10, 30, 14);
        jPanel3.add(txtMa);
        txtMa.setBounds(140, 10, 140, 20);

        jLabel6.setText("Lương CB");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(50, 100, 70, 14);

        txtLCB.setText("jTextField2");
        jPanel3.add(txtLCB);
        txtLCB.setBounds(140, 100, 140, 20);

        jLabel7.setText("PCCV");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(50, 190, 26, 14);

        txtPCCV.setText("jTextField3");
        jPanel3.add(txtPCCV);
        txtPCCV.setBounds(140, 190, 140, 20);

        jTextField1.setText("jTextField1");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(140, 260, 140, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Số ngày làm");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(50, 260, 70, 14);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 60, 400, 320);

        btnTinhLuong.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTinhLuong.setText("TÍNH");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });
        jPanel4.add(btnTinhLuong);

        lblTinh.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTinh.setText("Kết quả");
        jPanel4.add(lblTinh);

        txtKetQua.setText("jTextField1");
        jPanel4.add(txtKetQua);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 390, 1130, 50);

        tblLuong.setBackground(new java.awt.Color(204, 255, 204));
        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLuong);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 0, 730, 380);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
      String LCB= txtLCB.getText();
      String PCCV=txtPCCV.getText();
      double a= Double.parseDouble(LCB);
      double b= Double.parseDouble(PCCV);
      txtKetQua.setText("Lương "+(a*b));
    }//GEN-LAST:event_btnTinhLuongActionPerformed

    private void tblLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLuongMouseClicked
        int row=this.tblLuong.getSelectedRow();
        this.txtMa.setText((String)tblLuong.getValueAt(row,0));
        this.txtLCB.setText((String)tblLuong.getValueAt(row,1));
        this.txtPCCV.setText((String)tblLuong.getValueAt(row,2));
        
    }//GEN-LAST:event_tblLuongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LuongNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LuongNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTinh;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtLCB;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtPCCV;
    // End of variables declaration//GEN-END:variables
}
