/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyNVST;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HONG THAM
 */
public class PhongBan extends javax.swing.JFrame {
Connection conn= null;
Statement statement= null;
PreparedStatement preparedStatement;
ResultSet result = null;
DefaultTableModel dtmPhongBan;
int pos=1;
    /**
     * Creates new form PhongBan
     */
    public PhongBan() {
        initComponents();
        this.setTitle("Phòng Ban");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         this.setExtendedState(MAXIMIZED_BOTH);
         
        dtmPhongBan=(DefaultTableModel)this.tblPhongBan.getModel();
        ketNoiSCDL();
        HienThiDSPB();
        try {
            result.first();
            hienthiCTPB(result);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMaP = new javax.swing.JLabel();
        txtMaP = new javax.swing.JTextField();
        lblTenP = new javax.swing.JLabel();
        txtTenP = new javax.swing.JTextField();
        lblSDTP = new javax.swing.JLabel();
        txtSDTP = new javax.swing.JTextField();
        txtTruongPhong = new javax.swing.JTextField();
        lblTruongPhong = new javax.swing.JLabel();
        btnXoaP = new javax.swing.JButton();
        btnThemP = new javax.swing.JButton();
        btnThoatP = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhongBan = new javax.swing.JTable();
        btnTrangChu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(2, 2, 30, 15));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(176, 213, 208));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phòng Ban", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        lblMaP.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblMaP.setForeground(new java.awt.Color(255, 51, 0));
        lblMaP.setText("Mã phòng");

        lblTenP.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTenP.setForeground(new java.awt.Color(255, 0, 51));
        lblTenP.setText("Tên phòng");

        lblSDTP.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblSDTP.setForeground(new java.awt.Color(255, 0, 51));
        lblSDTP.setText("SĐT");

        lblTruongPhong.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblTruongPhong.setForeground(new java.awt.Color(255, 0, 51));
        lblTruongPhong.setText("Trưởng Phòng");

        btnXoaP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaP.setForeground(new java.awt.Color(51, 0, 204));
        btnXoaP.setText("Xóa");
        btnXoaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPActionPerformed(evt);
            }
        });

        btnThemP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThemP.setForeground(new java.awt.Color(0, 0, 153));
        btnThemP.setText("Thêm");
        btnThemP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPActionPerformed(evt);
            }
        });

        btnThoatP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThoatP.setForeground(new java.awt.Color(0, 0, 153));
        btnThoatP.setText("Thoát");
        btnThoatP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatPActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(51, 0, 204));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(102, 51, 0));

        tblPhongBan.setBackground(new java.awt.Color(205, 218, 226));
        tblPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "SĐT", "trưởng Phòng"
            }
        ));
        tblPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongBanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhongBan);

        jScrollPane3.setViewportView(jScrollPane2);

        btnTrangChu.setText("<<");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTenP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTenP, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(403, 403, 403))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnXoaP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThemP)))
                        .addGap(135, 135, 135))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTruongPhong)
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDTP, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTruongPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTrangChu))))
                            .addComponent(lblSDTP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuu)
                    .addComponent(btnThoatP))
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemP)
                            .addComponent(btnLuu))))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenP)
                    .addComponent(txtTenP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSDTP)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTruongPhong)
                            .addComponent(txtTruongPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSDTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnTrangChu)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoaP)
                            .addComponent(btnThoatP))
                        .addGap(83, 83, 83))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPActionPerformed
       txtMaP.setText("");
        txtTenP.setText("");
        txtSDTP.setText("");
        txtTruongPhong.setText("");
        txtMaP.requestFocus();
    }//GEN-LAST:event_btnThemPActionPerformed

    private void btnXoaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPActionPerformed
       
          int pos=this.tblPhongBan.getSelectedRow();
        if(pos>=0){
            String code=(String)(tblPhongBan.getValueAt(pos,0));
            if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa " +code+ " không")==JOptionPane.OK_OPTION){
                try{
                    String delete="DELETE FROM PHONGBAN WHERE MANV= '" +txtMaP.getText()+ "'";
                    statement.execute(delete);
                    HienThiDSPB();
                }
                catch(Exception ex){
                    
                }
            }
        }  
    }//GEN-LAST:event_btnXoaPActionPerformed

    private void btnThoatPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatPActionPerformed
        int n=JOptionPane.showConfirmDialog(null, "Thoát CT", "Thoát CT", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnThoatPActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
    
        if(KiemTraTonTai(txtMaP.getText())){
            int ret=JOptionPane.showConfirmDialog(null,"Mã ['"+txtMaP.getText()+"'] đã tồn tại bạn có muốn thêm không"
                    ,"Thông báo trùng mã",JOptionPane.YES_NO_CANCEL_OPTION);
            
            if(ret==JOptionPane.NO_OPTION)
                return;
            try{
                String update="Update PHONGBAN SET TENPH=N'"+txtTenP.getText()+"',SDT=N'"+txtSDTP.getText()+"', MATRUONGPHONG='"+txtTruongPhong.getText()+"' Where MAPH='"+txtMaP.getText()+"'";
                int x=statement.executeUpdate(update);
                if(x>=1)
                    HienThiDSPB();
            }
            catch(Exception ex){
                
            }           
        }
        else{
            try{
                String sqlInsert="Insert Into PHONGBAN Values('"+txtMaP.getText()+"',N'"+txtTenP.getText()+"','"+txtSDTP.getText()+"','"+txtTruongPhong.getText()+"')";
                int x=statement.executeUpdate(sqlInsert);
                if(x>0)
                   HienThiDSPB();
                
            }
            catch(Exception ex){
                
            }
        }
      
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongBanMouseClicked
       
        int row=this.tblPhongBan.getSelectedRow();
        this.txtMaP.setText((String)tblPhongBan.getValueAt(row,0));
        this.txtTenP.setText((String)tblPhongBan.getValueAt(row,1));
        this.txtSDTP.setText((String)tblPhongBan.getValueAt(row,2));
        this.txtTruongPhong.setText((String)tblPhongBan.getValueAt(row,3));
        
    }//GEN-LAST:event_tblPhongBanMouseClicked

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
         TrangChu t= new TrangChu();
      t.setVisible(true);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhongBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemP;
    private javax.swing.JButton btnThoatP;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoaP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMaP;
    private javax.swing.JLabel lblSDTP;
    private javax.swing.JLabel lblTenP;
    private javax.swing.JLabel lblTruongPhong;
    private javax.swing.JTable tblPhongBan;
    private javax.swing.JTextField txtMaP;
    private javax.swing.JTextField txtSDTP;
    private javax.swing.JTextField txtTenP;
    private javax.swing.JTextField txtTruongPhong;
    // End of variables declaration//GEN-END:variables

    private void ketNoiSCDL() {
       String strServerName = "DESKTOP-G8H4QG2\\SQLEXPRESS";
        String strDatabaseName = "QL_NVST";
        String strUserName = "sa";
        String strPassword = "6121999";
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionURL = "jdbc:sqlserver://" + strServerName
                                + ":1433;databaseName=" + strDatabaseName
                                +" ;user = " + strUserName + "; password = " +  strPassword;
            conn = DriverManager.getConnection(connectionURL);
            statement =conn.createStatement();
        }
        catch(SQLException ex1) {
        System.out.println("SQL Exception: " + ex1.toString());
        }
        catch(ClassNotFoundException ex2) {
                System.out.println("Class Not Found Exception: " + ex2.toString());
        }
    }

   

   
    
 private boolean KiemTraTonTai(String text) {
        try{
            String sqlSelect ="SELECT * FROM PHONGBAN WHERE MAPH= '"+text+"'";
            ResultSet rs=statement.executeQuery(sqlSelect);
            if(rs.next())
                return true;
            else
                return false;
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return false;
    }

    private void HienThiDSPB() {
       try{
            String sql="select * from PHONGBAN";
            result= statement.executeQuery(sql);
            dtmPhongBan.setRowCount(0);
            while(result.next())
            {
                String ma=result.getString("MAPH");
                String ten=result.getString("TENPH");
                String sdt=result.getString("SDT");
                String maTruongPhong=result.getString("MATRUONGPHONG");
           Vector<Object>vec= new Vector<Object>();
           vec.add(ma);
           vec.add(ten);
           vec.add(sdt);
           vec.add(maTruongPhong);
           dtmPhongBan.addRow(vec);
            }
            
        }catch(Exception ex)
        {}
    }

    private void hienthiCTPB(ResultSet rs) {
         try {
            txtMaP.setText(rs.getString("MAPB"));
            txtTenP.setText(rs.getString("TENPH"));
            txtSDTP.setText(rs.getString("SDTP"));
            txtTruongPhong.setText(rs.getString("MATRUONGPHONG"));
        } catch (Exception ex) {
            
        }
    }

  
}
